name: Build Angular App
  
on:
  workflow_dispatch

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python and NodeJS
        uses: bhoomikhurana/testing-composite-action@main
        

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
    
