name: Job Output

on:
  workflow_dispatch
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.set-output.outputs.age }}
    steps:
      - name: set-output
        id: set-output
        shell: bash
        run: echo "age=22" >> $GITHUB_OUTPUT

      - name: get-output
        run: echo ${{ steps.set-output.outputs.age }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: set-output2
        run: echo ${{ needs.job1.outputs.output_1}}
