name: Job Output

on:
  workflow_dispatch

env:
  CHANNEL_NAME: Interview Pro
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.set-output.outputs.age }}
    steps:
      - name: set-output
        id: set-output
        shell: bash
        run: |
          echo "age=22" >> $GITHUB_OUTPUT
          echo ${{ env.CHANNEL_NAME }}

      - name: get-output
        run: echo ${{ steps.set-output.outputs.age }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: set-output2
        run: |
          echo ${{ needs.job1.outputs.output_1}}
          echo ${{ env.CHANNEL_NAME }}
