name: Environment Setting

on:
  workflow_dispatch:
  
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Development
        run: echo "Deployed to Development"

  STAGE:
    runs-on: ubuntu-latest
    environment: STAGE
    needs: DEV
    steps:
      - name: Staging
        run: echo "Deployed to Staging"

  PROD:
     runs-on: ubuntu-latest
     environment: PROD
     needs: STAGE
     steps:
       - name: Production
         run: echo "Deployed to Production"
     

  
